-- =============================================
-- XXL-JOB 2.4.2 达梦数据库建表脚本
-- =============================================

-- 1. XXL_JOB_LOCK (必须先建，调度器初始化会锁)
CREATE TABLE XXL_JOB_LOCK (
    LOCK_NAME VARCHAR(50 CHAR) NOT NULL,
    PRIMARY KEY (LOCK_NAME)
);

INSERT INTO XXL_JOB_LOCK(LOCK_NAME) VALUES('UPDATE_INFO');

-- 2. XXL_JOB_GROUP
CREATE TABLE XXL_JOB_GROUP (
    ID INT IDENTITY(1,1) NOT NULL,
    APP_NAME VARCHAR(128 CHAR) NOT NULL,
    TITLE VARCHAR(128 CHAR) NOT NULL,
    ADDRESS_TYPE INT NOT NULL DEFAULT 0,
    ADDRESS_LIST VARCHAR(512 CHAR),
    UPDATE_TIME DATETIME(3),
    PRIMARY KEY (ID)
);

-- 3. XXL_JOB_INFO
CREATE TABLE XXL_JOB_INFO (
    ID INT IDENTITY(1,1) NOT NULL,
    JOB_GROUP INT NOT NULL,
    JOB_DESC VARCHAR(255 CHAR),
    ADD_TIME DATETIME(3),
    UPDATE_TIME DATETIME(3),
    AUTHOR VARCHAR(64 CHAR),
    ALARM_EMAIL VARCHAR(255 CHAR),
    SCHEDULE_TYPE VARCHAR(50 CHAR),
    SCHEDULE_CONF VARCHAR(128 CHAR),
    MISFIRE_STRATEGY VARCHAR(50 CHAR),
    EXECUTOR_ROUTE_STRATEGY VARCHAR(50 CHAR),
    EXECUTOR_HANDLER VARCHAR(255 CHAR),
    EXECUTOR_PARAM VARCHAR(512 CHAR),
    EXECUTOR_BLOCK_STRATEGY VARCHAR(50 CHAR),
    EXECUTOR_TIMEOUT INT DEFAULT 0,
    EXECUTOR_FAIL_RETRY_COUNT INT DEFAULT 0,
    GLUE_TYPE VARCHAR(50 CHAR),
    GLUE_SOURCE MTEXT,
    GLUE_REMARK VARCHAR(128 CHAR),
    GLUE_UPDATETIME DATETIME(3),
    CHILD_JOBID VARCHAR(255 CHAR),
    TRIGGER_STATUS INT DEFAULT 0,
    TRIGGER_LAST_TIME BIGINT DEFAULT 0,
    TRIGGER_NEXT_TIME BIGINT DEFAULT 0,
    PRIMARY KEY (ID)
);

-- 4. XXL_JOB_LOG
CREATE TABLE XXL_JOB_LOG (
    ID BIGINT IDENTITY(1,1) NOT NULL,
    JOB_GROUP INT NOT NULL,
    JOB_ID INT NOT NULL,
    EXECUTOR_ADDRESS VARCHAR(255 CHAR),
    EXECUTOR_HANDLER VARCHAR(255 CHAR),
    EXECUTOR_PARAM VARCHAR(512 CHAR),
    EXECUTOR_SHARDING_PARAM VARCHAR(128 CHAR),
    EXECUTOR_FAIL_RETRY_COUNT INT DEFAULT 0,
    TRIGGER_TIME DATETIME(3),
    TRIGGER_CODE INT NOT NULL DEFAULT 0,
    TRIGGER_MSG VARCHAR(2048 CHAR),
    HANDLE_TIME DATETIME(3),
    HANDLE_CODE INT NOT NULL DEFAULT 0,
    HANDLE_MSG VARCHAR(2048 CHAR),
    ALARM_STATUS INT DEFAULT 0,
    PRIMARY KEY (ID)
);

-- 5. XXL_JOB_LOGGLUE
CREATE TABLE XXL_JOB_LOGGLUE (
    ID INT IDENTITY(1,1) NOT NULL,
    JOB_ID INT NOT NULL,
    GLUE_TYPE VARCHAR(50 CHAR),
    GLUE_SOURCE MTEXT,
    GLUE_REMARK VARCHAR(128 CHAR),
    ADD_TIME DATETIME(3),
    UPDATE_TIME DATETIME(3),
    PRIMARY KEY (ID)
);

-- 6. XXL_JOB_LOG_REPORT
CREATE TABLE XXL_JOB_LOG_REPORT (
    ID INT IDENTITY(1,1) NOT NULL,
    TRIGGER_DAY DATETIME(3),
    RUNNING_COUNT INT DEFAULT 0,
    SUC_COUNT INT DEFAULT 0,
    FAIL_COUNT INT DEFAULT 0,
    PRIMARY KEY (ID)
);

-- 7. XXL_JOB_USER
CREATE TABLE XXL_JOB_USER (
    ID INT IDENTITY(1,1) NOT NULL,
    USERNAME VARCHAR(50 CHAR) NOT NULL,
    PASSWORD VARCHAR(50 CHAR) NOT NULL,
    ROLE TINYINT NOT NULL,
    PERMISSION VARCHAR(50 CHAR),
    PRIMARY KEY (ID)
);

-- 8. XXL_JOB_REGISTRY
CREATE TABLE XXL_JOB_REGISTRY (
    ID INT IDENTITY(1,1) NOT NULL,
    REGISTRY_GROUP VARCHAR(50 CHAR) NOT NULL,
    REGISTRY_KEY VARCHAR(255 CHAR) NOT NULL,
    REGISTRY_VALUE VARCHAR(512 CHAR),
    UPDATE_TIME DATETIME(3),
    PRIMARY KEY (ID)
);

-- 索引
CREATE INDEX IDX_XXL_JOB_INFO_JOB_GROUP ON XXL_JOB_INFO(JOB_GROUP);
CREATE INDEX IDX_XXL_JOB_LOG_TRIGGER_TIME ON XXL_JOB_LOG(TRIGGER_TIME);
CREATE INDEX IDX_XXL_JOB_LOG_JOB_GROUP_JOB_ID ON XXL_JOB_LOG(JOB_GROUP, JOB_ID);
CREATE INDEX IDX_XXL_JOB_LOGGLUE_JOB_ID ON XXL_JOB_LOGGLUE(JOB_ID);
CREATE INDEX IDX_XXL_JOB_LOG_REPORT_TRIGGER_DAY ON XXL_JOB_LOG_REPORT(TRIGGER_DAY);
CREATE INDEX IDX_XXL_JOB_REGISTRY_UPDATE_TIME ON XXL_JOB_REGISTRY(UPDATE_TIME);

-- 默认管理员账号 (密码: 123456, MD5)
SET IDENTITY_INSERT XXL_JOB_USER ON;
INSERT INTO XXL_JOB_USER(ID, USERNAME, PASSWORD, ROLE, PERMISSION) VALUES(1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);
SET IDENTITY_INSERT XXL_JOB_USER OFF;
